### ISSUE TITLE
[FEAT] Configuration example using Docker

### ISSUE THREAD

**Issue by SalahAdDin** [voxsar/medusa-plugin-typesense-voxsar#1]
Installing and configuring the plugin is easy, but we want to test it properly using Docker for Typesense.

Right now we have the following compose file:
```yaml
services:

  typesense:
    image: typesense/typesense:0.24.0
    environment:
      TYPESENSE_API_KEY: typesense-api-key
      TYPESENSE_DATA_DIR: /data
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    networks:
      - medusa-network
```

And we are setting up with the following `.env` variables:
```env
TYPESENSE_NODES=/etc/typesense/nodes
TYPESENSE_API_KEY=typesense-api-key
```

We are not sure about this.

Could you help us?

**Comment by SalahAdDin** [comment]
So, we updated the compose file adding the following:
```yaml
  typesense:
    image: typesense/typesense:27.0
    environment:
      TYPESENSE_API_KEY: typesense-api-key
      TYPESENSE_DATA_DIR: /data
    #ports:
    #  - "8108:8108"
    volumes:
      - typesense_data:/data
    networks:
      - medusa-network
    deploy:
      replicas: 3 # Number of Typesense nodes for high availability
      placement:
        constraints: [node.role == manager]

volumes:
  postgres_data:
  typesense_data:

networks:
  medusa-network:
    driver: bridge
```

And: 
```
TYPESENSE_NODES=http://typesense-node1:8108,http://typesense-node2:8108,http://typesense-node3:8108
TYPESENSE_API_KEY=typesense-api-key
```

But it gives up an error in the first node:
```
⠹ Initializing plugins
Request #1727285157196: Request to Node 0 failed due to "ERR_BAD_REQUEST Unsupported protocol typesense-1:"
⠸ Initializing plugins
Request #1727285157196: Request to Node 0 failed due to "ERR_BAD_REQUEST Unsupported protocol typesense-1:"
✔ 
``` 

Is it normal?
